###      **Women Cloth Reviews Prediction with Multi Nomial Naives Bayes**

**Objective**

  To develop a predictive model using Multi-  Nomial Naive Bayes that accurately classifies women's clothing reviews into categories such as positive, negative, or neutral sentiment, thereby providing valuable insights into customer opinions and enhancing decision-making for fashion retailers.

**Import Library**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

**Import Dataset**

In [3]:
dress = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")

**Import Data**

In [4]:
dress.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


**Describe Data**

In [5]:
dress.describe()

Clothing ID           Age        Rating   Recommended  \
count  23486.000000  23486.000000  23486.000000  23486.000000   
mean     918.118709     43.198544      4.196032      0.822362   
std      203.298980     12.279544      1.110031      0.382216   
min        0.000000     18.000000      1.000000      0.000000   
25%      861.000000     34.000000      4.000000      1.000000   
50%      936.000000     41.000000      5.000000      1.000000   
75%     1078.000000     52.000000      5.000000      1.000000   
max     1205.000000     99.000000      5.000000      1.000000   

       Positive Feedback  
count       23486.000000  
mean            2.535936  
std             5.702202  
min             0.000000  
25%             0.000000  
50%             1.000000  
75%             3.000000  
max           122.000000

**Data Visualization**

In [6]:
dress.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [7]:
dress.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [8]:
dress.shape

(23486, 10)

**Data Preprocessing**

In [ ]:
dress.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
dress[dress['Review']==""] = np.NaN
dress['Review'].fillna("No review is given", inplace=True)
dress.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
dress['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

**Define Target Variable (y) and Feature Variables (X)**

In [ ]:
x = dress['Review']
y = dress['Rating']
dress['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

**Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, stratify=y, random_state=2529)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)
x_train = cv.fit_transform(x_train)
cv.get_feature_names_out()

array(['00 big', '00 fits', '00 petite', ..., 'zipper zip',
       'zippered pockets', 'zippers buttons'], dtype=object)

In [ ]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x_test = cv.fit_transform(x_test)
cv.get_feature_names_out()

array(['00 24', '00 petite', '00 sold', ..., 'zipper split',
       'zipper sturdy', 'zippers buttons'], dtype=object)

In [ ]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**Modeling**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

**Model Prediction**

In [ ]:
y_pred = model.predict(x_test)
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1., 2., 5., ..., 4., 3., 1.])

In [ ]:
model.predict_proba(x_test)

array([[0.45433767, 0.08215679, 0.44111678, 0.00904855, 0.01334022],
       [0.08538546, 0.53197259, 0.36096501, 0.00370374, 0.01797319],
       [0.04978519, 0.07954803, 0.11784385, 0.31199241, 0.44083052],
       ...,
       [0.07871327, 0.0343138 , 0.02156397, 0.8608945 , 0.00451447],
       [0.09545745, 0.00239741, 0.84956399, 0.01241549, 0.04016567],
       [0.65456291, 0.01868614, 0.14266667, 0.04591333, 0.13817096]])

**Model Evaluation**

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))


[[  65   41   46   37   64]
 [ 158   75   57   80  100]
 [ 280  176  138  115  152]
 [ 539  297  217  201  269]
 [1237  777  619  533  773]]


In [ ]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n         1.0       0.03      0.26      0.05       253\n         2.0       0.05      0.16      0.08       470\n         3.0       0.13      0.16      0.14       861\n         4.0       0.21      0.13      0.16      1523\n         5.0       0.57      0.20      0.29      3939\n\n    accuracy                           0.18      7046\n   macro avg       0.20      0.18      0.15      7046\nweighted avg       0.38      0.18      0.22      7046\n'


**Explanation:**

1. **Context:** In the world of fashion and e-commerce, understanding customer sentiment is crucial for businesses to make informed decisions. Customer reviews play a vital role in gauging the popularity and satisfaction levels of products.

2. **Objective:** The primary goal of this machine learning project is to build a predictive model that can automatically classify women's clothing reviews based on their sentiment. Sentiment analysis helps identify whether a review is positive, negative, or neutral.

3. **Methodology:** The chosen methodology for this project is the Multi-Nomial Naive Bayes algorithm. Naive Bayes is a probabilistic classification algorithm that works well with text data, making it suitable for sentiment analysis.

4. **Data Collection:** To train and evaluate the model, a dataset of women's clothing reviews will be collected. This dataset will ideally consist of text reviews and corresponding sentiment labels (positive, negative, or neutral) provided by customers.

5. **Data Preprocessing:** Before feeding the data into the model, it will undergo preprocessing steps. This includes tasks such as text tokenization, removing stop words, and transforming the text into numerical features that the algorithm can work with.

6. **Model Training:** The Multi-Nomial Naive Bayes model will be trained on a portion of the dataset. During training, the algorithm learns the patterns and relationships between words and sentiments in the reviews.

7. **Model Evaluation:** To assess the model's performance, it will be tested on a separate dataset (not used during training). Common evaluation metrics include accuracy, precision, recall, and F1-score.

8. **Deployment:** Once the model proves to be accurate and reliable, it can be deployed for real-time sentiment analysis of women's clothing reviews. This can be integrated into an e-commerce website or used for regular analysis of customer feedback.

9. **Benefits:** The project's outcomes include providing fashion retailers with valuable insights into customer opinions, helping them identify areas of improvement, popular products, and overall customer satisfaction levels. It can also assist in decision-making related to inventory management, marketing strategies, and product development.

10. **Future Enhancements:** Depending on the project's success, future enhancements could involve incorporating more advanced natural language processing techniques, expanding the model to handle multiclass classification, or adapting it for other product categories.

In summary, this project aims to leverage machine learning, specifically Multi-Nomial Naive Bayes, to automate sentiment analysis of women's clothing reviews, enabling businesses to make data-driven decisions and enhance customer satisfaction.